plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'lib/p1_tool/application/live_smoke_runner.rb'

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Exclude:
    - 'spec/test_helper.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/test_helper.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/p1_tool/core/configuration_schema.rb'
    - 'lib/p1_tool/application/contracts/**/payload_schema.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/test_helper.rb'

Metrics/ParameterLists:
  Exclude:
    - 'spec/test_helper.rb'
    - 'lib/p1_tool/runtime/execution_context.rb'
    - 'lib/p1_tool/runtime/task_processor.rb'
    - 'lib/p1_tool/gateways/p1/transports/http.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false
